## Evidencia 1 - Pregunta 1- Resolver sistemas de ecuaciones

Resuelve las siguientes ecuaciones lineales:
* a. $$8x + 5y + 3z - 6w = 41$$
$$15x - 3y + 4z + 7w = 13$$
$$x + 6y - 2z + w = -12$$
$$-2x + y + 7z - 3w = 0$$
* b. $$x + 4z = 14$$
$$5x + 3y + 2z = 25$$
$$3x + 4y = -12$$

In [1]:
import numpy as np

**Para el sistema de ecuaciones a. se crea la matriz de coeficientes y la matriz de resultados:**

In [4]:
matriz_a = np.array([[8, 5, 3, -6], [15, -3, 4, 7], [1, 6, -2, 1], [-2, 1, 7, -3]])
print("La matriz de coeficientes A es:\n",matriz_a)
matriz_a_resultados = np.array([41, 13, -12, 0])
print("La matriz de resultados A es:\n",matriz_a_resultados)

La matriz de coeficientes es:
 [[ 8  5  3 -6]
 [15 -3  4  7]
 [ 1  6 -2  1]
 [-2  1  7 -3]]
La matriz de resultados es:
 [ 41  13 -12   0]


**Se obtienen las soluciones usando el método solve de la librería numpy:**

In [5]:
soluciones_a = np.linalg.solve(matriz_a, matriz_a_resultados)
print("Las soluciones del sistema de ecuaciones A son:\n",soluciones_a)

Las soluciones del sistema de ecuaciones a son:
 [ 3.03126383 -2.00339183 -0.96681905 -4.94455095]


**Para el sistema de ecuaciones b. se crea la matriz de coeficientes y la matriz de resultados:**

In [7]:
matriz_b = np.array([[1, 0, 4], [5, 3, 2], [3, 4, 0]])
print("La matriz de coeficientes B es:\n",matriz_b)
matriz_b_resultados = np.array([14, 25, -12])
print("La matriz de resultados B es:\n",matriz_b_resultados)

La matriz de coeficientes B es:
 [[1 0 4]
 [5 3 2]
 [3 4 0]]
La matriz de resultados B es:
 [ 14  25 -12]


**Se obtienen las soluciones usando el método solve de la librería numpy:**

In [8]:
soluciones_b = np.linalg.solve(matriz_b, matriz_b_resultados)
print("Las soluciones del sistema de ecuaciones B son:\n",soluciones_b)

Las soluciones del sistema de ecuaciones B son:
 [ 12.  -12.    0.5]
