## Tetramestre 3 - Actividad 1

__Pregunta 3__
A continuación se describen los resultados correspondientes al punto 5 de la actividad 1. El enunciado de ese punto se muestra en el siguiente párrafo.

Genera un nuevo cuaderno de Jupyter Notebook y resuelve los siguientes sistemas de ecuaciones lineales, encontrando los valores de las variables utilizando diferentes métodos:

* a $$x + 2y + 5z - 4w = 21$$
$$5x + 8y + z +w = 8$$
$$5x + 7y - 3z + 2w = 14$$
$$—x + 3y + 9z -w = 5$$

* b $$6x + 8z = 9$$
$$2x + 3y + z = 15$$
$$4x + y = -4$$

**Solución con matriz inversa**
* Proceso de solución para el punto a

Método 1

In [1]:
import numpy as np

**Creando la matriz de coeficientes, resultados y obteniendo determinante**

In [4]:
matriz_a = np.array([[1,2,5,-4],[5,8,1,1],[5,7,-3,2],[-1,3,9,-1]])
matriz_a_resultados = np.array([[21],[8],[14],[5]])
print("Matriz de coeficientes:\n", matriz_a)
print("Matriz de resultados:\n", matriz_a_resultados)

#Calculando determinante de la matriz a
det_a = np.linalg.det(matriz_a)
print("Determinante de la matriz a:\n", det_a)

Matriz de coeficientes:
 [[ 1  2  5 -4]
 [ 5  8  1  1]
 [ 5  7 -3  2]
 [-1  3  9 -1]]
Matriz de resultados:
 [[21]
 [ 8]
 [14]
 [ 5]]
Determinante de la matriz a:
 114.00000000000003


**Obteniendo matriz inversa y resultados**

In [5]:
#Obteniendo producto interno con la matriz de resultados
if det_a == 0:
    print("La matriz no tiene inversa")
else:
    matriz_a_inversa = np.linalg.inv(matriz_a)
    matriz_a_resultados_inversa = np.dot(matriz_a_inversa, matriz_a_resultados)
    print("matriz con las soluciones:\n", matriz_a_resultados_inversa)

matriz con las soluciones:
 [[-22.19298246]
 [ 17.73684211]
 [ -9.33333333]
 [-13.59649123]]


Método 2
- Se puede calcular tambien de la siguiente forma usando el producto interno directo en la inversa de la matriz a

In [6]:
matriz_a_resultado2 = matriz_a_inversa.dot(matriz_a_resultados)
print("matriz con las soluciones:\n", matriz_a_resultado2)

matriz con las soluciones:
 [[-22.19298246]
 [ 17.73684211]
 [ -9.33333333]
 [-13.59649123]]


* Usando el método directo "solve"

In [9]:
matriz_resultado_solve = np.linalg.solve(matriz_a, matriz_a_resultados)
print("matriz con las soluciones:\n", matriz_resultado_solve)

matriz con las soluciones:
 [[-22.19298246]
 [ 17.73684211]
 [ -9.33333333]
 [-13.59649123]]


* Proceso de solución para el punto b

Método 1 (Se requiere haber importado numpy al inicio de este ejercicio)

**Creando la matriz de coeficientes, resultados y obteniendo determinante**

In [11]:
matriz_b = np.array([[6,0,8],[2,3,1],[4,1,0]])
matriz_b_resultados = np.array([[9],[15],[-4]])
print("Matriz de coeficientes:\n", matriz_b)
print("Matriz de resultados:\n", matriz_b_resultados)

det_b = np.linalg.det(matriz_b)
print("Determinante de la matriz b:\n", det_b)

Matriz de coeficientes:
 [[6 0 8]
 [2 3 1]
 [4 1 0]]
Matriz de resultados:
 [[ 9]
 [15]
 [-4]]
Determinante de la matriz b:
 -85.99999999999997


**Obteniendo matriz inversa y resultados**

In [12]:
#Obteniendo producto interno con la matriz de resultados
if det_b == 0:
    print("La matriz no tiene inversa")
else:
    matriz_b_inversa = np.linalg.inv(matriz_b)
    matriz_b_resultados_inversa = np.dot(matriz_b_inversa, matriz_b_resultados)
    print("matriz con las soluciones:\n", matriz_b_resultados_inversa)

matriz con las soluciones:
 [[-2.40697674]
 [ 5.62790698]
 [ 2.93023256]]


Método 2
- Se puede calcular tambien de la siguiente forma usando el producto interno directo en la inversa de la matriz b

In [13]:
matriz_b_resultado2 = matriz_b_inversa.dot(matriz_b_resultados)
print("matriz con las soluciones:\n", matriz_b_resultado2)

matriz con las soluciones:
 [[-2.40697674]
 [ 5.62790698]
 [ 2.93023256]]


* Usando el método directo "solve"

In [14]:
matriz_resultado_solve = np.linalg.solve(matriz_b, matriz_b_resultados)
print("matriz con las soluciones:\n", matriz_resultado_solve)

matriz con las soluciones:
 [[-2.40697674]
 [ 5.62790698]
 [ 2.93023256]]
