## Tetramestre 3 - Actividad 1

__Pregunta 3__

A continuación se describen los resultados correspondientes al punto 3 de la actividad 1. El enunciado de ese punto se muestra en el siguiente párrafo.

Utilizando un cuaderno de Jupyter Notebook y el lenguaje de programación Python, realiza las siguientes operaciones:
* Genera una matriz cuadrada de 4x4.
* Calcula su inversa y su traspuesta.
* Multiplica la matriz por un escalar.
* Realiza el producto interno con una nueva matriz de dimensiones 4x2.



In [1]:
import numpy as np

**Generación de la matriz cuadrada de 4x4**

In [4]:
matriz_4x4 = np.array([[5,6,7,8],[20,4,1,12],[9,10,11,12],[13,14,15,16]])
print("Matriz cuadrada de 4x4:\n",matriz_4x4)

Matriz cuadrada de 4x4:
 [[ 5  6  7  8]
 [20  4  1 12]
 [ 9 10 11 12]
 [13 14 15 16]]


**Inversa de la matriz cuadrada de 4x4**

In [5]:
determinante = np.linalg.det(matriz_4x4)
if(determinante == 0):
    print("La matriz no tiene inversa")
else:
    matriz_inversa = np.linalg.inv(matriz_4x4)
    print("Matriz inversa de la matriz cuadrada de 4x4:\n",matriz_inversa)

Matriz inversa de la matriz cuadrada de 4x4:
 [[-7.57817245e+13  3.69591346e-02  1.51563449e+14 -7.57817245e+13]
 [ 2.21932193e+14 -3.68088942e-02 -4.43864386e+14  2.21932193e+14]
 [-2.16519213e+14 -3.72596154e-02  4.33038426e+14 -2.16519213e+14]
 [ 7.03687442e+13  3.71093750e-02 -1.40737488e+14  7.03687442e+13]]


**Multiplicación de la matriz cuadrada de 4x4 por un escalar**

In [6]:
escalar = 2
matriz_producto_escalar = matriz_4x4 * escalar
print("Matriz cuadrada de 4x4 multiplicada por un escalar:\n",matriz_producto_escalar)

Matriz cuadrada de 4x4 multiplicada por un escalar:
 [[10 12 14 16]
 [40  8  2 24]
 [18 20 22 24]
 [26 28 30 32]]


**Producto interno de la matriz cuadrada de 4x4 por una nueva matriz de dimensiones 4x2**

In [9]:
matriz_4x2 = np.array([[12,5],[8,2],[5,6],[7,8]])
matriz_producto_interno = np.dot(matriz_4x4,matriz_4x2)
print("Producto interno de la matriz cuadrada de 4x4 por una nueva matriz de dimensiones 4x2:\n",matriz_producto_interno)

Producto interno de la matriz cuadrada de 4x4 por una nueva matriz de dimensiones 4x2:
 [[199 143]
 [361 210]
 [327 227]
 [455 311]]
