In [1]:
import numpy as np

import matplotlib.pyplot as plt
import numpy as np

In [7]:
A = np.array([[1.2, 0.9],[0, -0.4]])
x = np.array([-0.4902, 0.8715])

In [8]:
y = A@x
print(y)

print(A)

[ 0.19611 -0.3486 ]
[[ 1.2  0.9]
 [ 0.  -0.4]]


In [9]:
det_A = np.linalg.det(A)
print(det_A)

-0.48


In [10]:
rango_A = np.linalg.matrix_rank(A)
print(rango_A)

2


In [11]:
#otro valor del de las matrices es la traza no se agrega aqui
#encontrar los coeficientes del polinomio caracteristicos y despues encontrar las raíces
coef = np.poly(A)
print(coef)

[ 1.   -0.8  -0.48]


In [13]:
#encontrar las raíces
roots = np.roots(coef)
print(roots)

[ 1.2 -0.4]


In [16]:
#datos de la matriz
datos_matriz = np.linalg.eig(A)
print(datos_matriz)

(array([ 1.2, -0.4]), array([[ 1.        , -0.49026124],
       [ 0.        ,  0.87157554]]))


In [20]:
autov1 = datos_matriz[1][:,0] # obtiene los valores de los renglones en la columna 0
print(autov1)

[1. 0.]


In [22]:
autov2 = datos_matriz[1][:,1] #obtiene los valores en los renglones en al columna 1
print(autov2)

[-0.49026124  0.87157554]


* La autodescomposición solo funciona para matrices cuadradas

In [ ]:
#Hay dos transformaciones asociadas con la matriz cuando se hade la autodescomposición
#Hay diferentes autovalores que corresponden a cada autovector
